#!/usr/bin/env python3
# Copyright (C) 2026 Matrox Graphics Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Validate all IPMX video test streams generated by generate_video_test_streams.py.

For each stream in test-streams/:
  - Clear streams: full validation with --hrd-timing (all 3 HRD tiers),
    --sdp cross-validation, and --allow-superset-profile.
  - Encrypted streams: validation with --sdp, --allow-superset-profile,
    and the appropriate --hkep / --pep flags.  HRD tiers are omitted
    because the payload is not accessible.

Run:
  python3 validate_video_test_streams.py [--output-dir DIR] [--codec h264|h265]
                                         [--config NAME] [--verbose] [--full-report]

Requires: the video test streams to have been generated first via
  python3 generate_video_test_streams.py
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from dataclasses import dataclass
from enum import Enum, auto
from pathlib import Path

from generate_video_test_streams import (
    ALL_CONFIGS,
    DEFAULT_OUTPUT_DIR,
    EncryptionMode,
    StreamConfig,
)


SCRIPT_DIR = Path(__file__).resolve().parent
JXSV_STREAMS_DIR = SCRIPT_DIR / "jxsv-streams"

ENCRYPTION_SUFFIXES: list[tuple[str, list[str]]] = [
    ("_hkep", ["--hkep"]),
    ("_pep", ["--pep"]),
    ("_hkep_pep", ["--hkep", "--pep"]),
]

@dataclass
class JxsvStreamDef:
    """Definition of a manually curated JXSV test stream."""
    stem: str
    enc_flags: list[str]
    exactframerate: str | None = None


class Outcome(Enum):
    PASS = auto()
    FAIL = auto()
    ERROR = auto()
    SKIP = auto()


@dataclass
class ValidationResult:
    name: str
    outcome: Outcome
    shall_pass: int = 0
    shall_fail: int = 0
    shall_untestable: int = 0
    should_pass: int = 0
    should_fail: int = 0
    should_untestable: int = 0
    failures: list[str] | None = None
    error: str | None = None


def _parse_summary_line(line: str) -> tuple[int, int, int] | None:
    """Parse '52/52 passed, 0 failed, 23 cannot test' into (pass, fail, untestable)."""
    try:
        parts = line.strip().split(",")
        passed = int(parts[0].split("/")[0])
        failed = int(parts[1].strip().split()[0])
        untestable = int(parts[2].strip().split()[0]) if len(parts) >= 3 else 0
        return passed, failed, untestable
    except (IndexError, ValueError):
        return None


def validate_stream(
    pcap: Path,
    sdp: Path,
    cfg: StreamConfig,
    encrypted: bool,
    enc_flags: list[str],
    verbose: bool,
    full_report: bool,
) -> ValidationResult:
    """Run the appropriate validator on a single stream."""
    name = pcap.stem

    if cfg.codec == "h265":
        validator = SCRIPT_DIR / "ipmx_h265_validate_pcap.py"
    else:
        validator = SCRIPT_DIR / "ipmx_h264_validate_pcap.py"

    cmd: list[str] = [
        sys.executable, str(validator), str(pcap),
        "--exactframerate", cfg.exactframerate_arg,
        "--sdp", str(sdp),
        "--allow-superset-profile",
    ]

    if not encrypted:
        cmd.append("--hrd-timing")

    cmd.extend(enc_flags)

    if full_report:
        cmd.append("--full-report")

    try:
        proc = subprocess.run(
            cmd, capture_output=True, text=True, timeout=600,
        )
    except subprocess.TimeoutExpired:
        return ValidationResult(
            name=name, outcome=Outcome.ERROR,
            error="Validator timed out after 600s",
        )
    except Exception as exc:
        return ValidationResult(
            name=name, outcome=Outcome.ERROR,
            error=str(exc),
        )

    output = proc.stdout + proc.stderr

    if proc.returncode != 0 and "does not exist" in output:
        return ValidationResult(
            name=name, outcome=Outcome.ERROR,
            error=f"Validator error: {output.strip()[-200:]}",
        )

    result = ValidationResult(name=name, outcome=Outcome.PASS)

    fail_lines: list[str] = []
    for line in output.splitlines():
        stripped = line.strip()
        if stripped.startswith("SHALL requirements"):
            continue
        if stripped.startswith("SHOULD requirements"):
            continue

        summary = _parse_summary_line(stripped)
        if summary is not None:
            p, f, u = summary
            if result.shall_pass == 0 and result.should_pass == 0:
                result.shall_pass = p
                result.shall_fail = f
                result.shall_untestable = u
            else:
                result.should_pass = p
                result.should_fail = f
                result.should_untestable = u
            continue

        if stripped.startswith("FAIL "):
            fail_lines.append(stripped)

    if result.shall_fail > 0 or fail_lines:
        result.outcome = Outcome.FAIL
        result.failures = fail_lines

    if verbose and output.strip():
        for line in output.splitlines():
            print(f"    {line}")

    return result


JXSV_STREAMS: list[JxsvStreamDef] = [
    JxsvStreamDef(stem="jxsv_2160p60_rgb_8_clear", enc_flags=[],
                  exactframerate="60"),
    JxsvStreamDef(stem="jxsv_2160p60_444_8_hkep", enc_flags=["--hkep"],
                  exactframerate="60"),
    JxsvStreamDef(stem="jxsv_1080p5994_rgb_8_pep", enc_flags=["--pep"],
                  exactframerate="60000/1001"),
]


def validate_jxsv_stream(
    pcap: Path,
    sdp: Path,
    jdef: JxsvStreamDef,
    verbose: bool,
    full_report: bool,
) -> ValidationResult:
    """Run the JXSV validator on a single stream."""
    name = pcap.stem
    validator = SCRIPT_DIR / "ipmx_jxsv_validate_pcap.py"

    cmd: list[str] = [
        sys.executable, str(validator), str(pcap),
        "--sdp", str(sdp),
    ]
    if jdef.exactframerate:
        cmd.extend(["--exactframerate", jdef.exactframerate])
    cmd.extend(jdef.enc_flags)
    if full_report:
        cmd.append("--full-report")

    try:
        proc = subprocess.run(
            cmd, capture_output=True, text=True, timeout=600,
        )
    except subprocess.TimeoutExpired:
        return ValidationResult(
            name=name, outcome=Outcome.ERROR,
            error="Validator timed out after 600s",
        )
    except Exception as exc:
        return ValidationResult(
            name=name, outcome=Outcome.ERROR,
            error=str(exc),
        )

    output = proc.stdout + proc.stderr

    if proc.returncode != 0 and "does not exist" in output:
        return ValidationResult(
            name=name, outcome=Outcome.ERROR,
            error=f"Validator error: {output.strip()[-200:]}",
        )

    result = ValidationResult(name=name, outcome=Outcome.PASS)

    fail_lines: list[str] = []
    for line in output.splitlines():
        stripped = line.strip()
        if stripped.startswith("SHALL requirements"):
            continue
        if stripped.startswith("SHOULD requirements"):
            continue

        summary = _parse_summary_line(stripped)
        if summary is not None:
            p, f, u = summary
            if result.shall_pass == 0 and result.should_pass == 0:
                result.shall_pass = p
                result.shall_fail = f
                result.shall_untestable = u
            else:
                result.should_pass = p
                result.should_fail = f
                result.should_untestable = u
            continue

        if stripped.startswith("FAIL "):
            fail_lines.append(stripped)

    if result.shall_fail > 0 or fail_lines:
        result.outcome = Outcome.FAIL
        result.failures = fail_lines

    if verbose and output.strip():
        for line in output.splitlines():
            print(f"    {line}")

    return result


def main() -> int:
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR,
        help=f"Test streams directory (default: {DEFAULT_OUTPUT_DIR})",
    )
    parser.add_argument(
        "--codec", choices=["h264", "h265", "jxsv"],
        help="Validate only a specific codec",
    )
    parser.add_argument(
        "--config", type=str,
        help="Validate only a specific config by name",
    )
    parser.add_argument("-v", "--verbose", action="store_true")
    parser.add_argument(
        "--full-report", action="store_true",
        help="Pass --full-report to validators (show all checks)",
    )
    args = parser.parse_args()

    configs = ALL_CONFIGS
    if args.codec:
        configs = [c for c in configs if c.codec == args.codec]
    if args.config:
        configs = [c for c in configs if c.name == args.config]
        if not configs:
            raise SystemExit(
                f"Unknown config '{args.config}'. "
                f"Available: {', '.join(c.name for c in ALL_CONFIGS)}"
            )

    if configs and not args.output_dir.exists():
        raise SystemExit(f"Output directory does not exist: {args.output_dir}")

    results: list[ValidationResult] = []
    total_checks = 0

    # --- Clear streams ---
    if configs:
        print("=" * 70)
        print("CLEAR STREAMS")
        print("=" * 70)
    for cfg in configs:
        codec_dir = args.output_dir / cfg.codec
        pcap = codec_dir / f"{cfg.name}.pcap"
        sdp = codec_dir / f"{cfg.name}.sdp"

        if not pcap.exists():
            print(f"  SKIP {cfg.name} — PCAP not found")
            results.append(ValidationResult(
                name=cfg.name, outcome=Outcome.SKIP,
            ))
            continue
        if not sdp.exists():
            print(f"  SKIP {cfg.name} — SDP not found")
            results.append(ValidationResult(
                name=cfg.name, outcome=Outcome.SKIP,
            ))
            continue

        r = validate_stream(
            pcap, sdp, cfg,
            encrypted=False, enc_flags=[],
            verbose=args.verbose, full_report=args.full_report,
        )
        results.append(r)
        checks = r.shall_pass + r.shall_fail + r.should_pass + r.should_fail
        total_checks += checks

        if r.outcome == Outcome.PASS:
            print(f"  PASS {cfg.name} "
                  f"(SHALL {r.shall_pass}/{r.shall_pass + r.shall_fail}, "
                  f"SHOULD {r.should_pass}/{r.should_pass + r.should_fail})")
        elif r.outcome == Outcome.FAIL:
            print(f"  FAIL {cfg.name} "
                  f"(SHALL {r.shall_pass}/{r.shall_pass + r.shall_fail}, "
                  f"SHOULD {r.should_pass}/{r.should_pass + r.should_fail})")
            if r.failures:
                for f in r.failures:
                    print(f"       {f}")
        elif r.outcome == Outcome.ERROR:
            print(f"  ERR  {cfg.name} — {r.error}")

    # --- Encrypted streams ---
    if configs:
        print()
        print("=" * 70)
        print("ENCRYPTED STREAMS")
        print("=" * 70)
    for cfg in configs:
        codec_dir = args.output_dir / cfg.codec
        for suffix, enc_flags in ENCRYPTION_SUFFIXES:
            enc_name = f"{cfg.name}{suffix}"
            pcap = codec_dir / f"{enc_name}.pcap"
            sdp = codec_dir / f"{enc_name}.sdp"

            if not pcap.exists():
                continue
            if not sdp.exists():
                print(f"  SKIP {enc_name} — SDP not found")
                results.append(ValidationResult(
                    name=enc_name, outcome=Outcome.SKIP,
                ))
                continue

            r = validate_stream(
                pcap, sdp, cfg,
                encrypted=True, enc_flags=enc_flags,
                verbose=args.verbose, full_report=args.full_report,
            )
            results.append(r)
            checks = r.shall_pass + r.shall_fail + r.should_pass + r.should_fail
            total_checks += checks

            if r.outcome == Outcome.PASS:
                print(f"  PASS {enc_name} "
                      f"(SHALL {r.shall_pass}/{r.shall_pass + r.shall_fail}, "
                      f"SHOULD {r.should_pass}/{r.should_pass + r.should_fail})")
            elif r.outcome == Outcome.FAIL:
                print(f"  FAIL {enc_name} "
                      f"(SHALL {r.shall_pass}/{r.shall_pass + r.shall_fail}, "
                      f"SHOULD {r.should_pass}/{r.should_pass + r.should_fail})")
                if r.failures:
                    for f in r.failures:
                        print(f"       {f}")
            elif r.outcome == Outcome.ERROR:
                print(f"  ERR  {enc_name} — {r.error}")

    # --- JXSV streams ---
    if args.codec is None or args.codec == "jxsv":
        print()
        print("=" * 70)
        print("JXSV STREAMS")
        print("=" * 70)
        if JXSV_STREAMS_DIR.exists():
            for jdef in JXSV_STREAMS:
                pcap = JXSV_STREAMS_DIR / f"{jdef.stem}.pcap"
                sdp = JXSV_STREAMS_DIR / f"{jdef.stem}.sdp"
                if not pcap.exists():
                    print(f"  SKIP {jdef.stem} — PCAP not found")
                    results.append(ValidationResult(
                        name=jdef.stem, outcome=Outcome.SKIP,
                    ))
                    continue
                if not sdp.exists():
                    print(f"  SKIP {jdef.stem} — SDP not found")
                    results.append(ValidationResult(
                        name=jdef.stem, outcome=Outcome.SKIP,
                    ))
                    continue

                r = validate_jxsv_stream(
                    pcap, sdp, jdef,
                    verbose=args.verbose, full_report=args.full_report,
                )
                results.append(r)
                checks = r.shall_pass + r.shall_fail + r.should_pass + r.should_fail
                total_checks += checks

                if r.outcome == Outcome.PASS:
                    print(f"  PASS {jdef.stem} "
                          f"(SHALL {r.shall_pass}/{r.shall_pass + r.shall_fail}, "
                          f"SHOULD {r.should_pass}/{r.should_pass + r.should_fail})")
                elif r.outcome == Outcome.FAIL:
                    print(f"  FAIL {jdef.stem} "
                          f"(SHALL {r.shall_pass}/{r.shall_pass + r.shall_fail}, "
                          f"SHOULD {r.should_pass}/{r.should_pass + r.should_fail})")
                    if r.failures:
                        for f in r.failures:
                            print(f"       {f}")
                elif r.outcome == Outcome.ERROR:
                    print(f"  ERR  {jdef.stem} — {r.error}")
        else:
            print(f"  SKIP — {JXSV_STREAMS_DIR} not found")

    # --- Summary ---
    passed = sum(1 for r in results if r.outcome == Outcome.PASS)
    failed = sum(1 for r in results if r.outcome == Outcome.FAIL)
    errors = sum(1 for r in results if r.outcome == Outcome.ERROR)
    skipped = sum(1 for r in results if r.outcome == Outcome.SKIP)

    print()
    print("=" * 70)
    print(f"SUMMARY: {passed} passed, {failed} failed, "
          f"{errors} errors, {skipped} skipped "
          f"({len(results)} streams, {total_checks} checks)")
    print("=" * 70)

    if failed > 0 or errors > 0:
        fail_results = [r for r in results if r.outcome in (Outcome.FAIL, Outcome.ERROR)]
        print("\nFailed/errored streams:")
        for r in fail_results:
            if r.outcome == Outcome.FAIL and r.failures:
                for f in r.failures:
                    print(f"  {r.name}: {f}")
            elif r.outcome == Outcome.ERROR:
                print(f"  {r.name}: ERROR — {r.error}")

    return 1 if (failed > 0 or errors > 0) else 0


if __name__ == "__main__":
    raise SystemExit(main())
